package net.lax1dude.eaglercraft.v1_8.opengl.ext.deferred;

/**
 * Copyright (c) 2023 lax1dude. All Rights Reserved.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 */
public class ExtGLEnums {

	public static final int _GL_FRAMEBUFFER = 0x8D40;
	public static final int _GL_READ_FRAMEBUFFER = 0x8CA8;
	public static final int _GL_DRAW_FRAMEBUFFER = 0x8CA9;
	public static final int _GL_RENDERBUFFER = 0x8D41;
	public static final int _GL_COLOR_ATTACHMENT0 = 0x8CE0;
	public static final int _GL_COLOR_ATTACHMENT1 = 0x8CE1;
	public static final int _GL_COLOR_ATTACHMENT2 = 0x8CE2;
	public static final int _GL_COLOR_ATTACHMENT3 = 0x8CE3;
	public static final int _GL_DEPTH_ATTACHMENT = 0x8D00;
	public static final int _GL_DEPTH_COMPONENT = 0x1902;
	public static final int _GL_DEPTH_COMPONENT24 = 0x81A6;
	public static final int _GL_DEPTH_COMPONENT32F = 0x8CAC;
	public static final int _GL_R8 = 0x8229;
	public static final int _GL_RG = 0x8227;
	public static final int _GL_RG8 = 0x822B;
	public static final int _GL_RGB16F = 0x881B;
	public static final int _GL_HALF_FLOAT = 0x140B;
	public static final int _GL_UNIFORM_BUFFER = 0x8A11;
	public static final int _GL_TEXTURE_COMPARE_MODE = 0x884C;
	public static final int _GL_TEXTURE_COMPARE_FUNC = 0x884D;
	public static final int _GL_COMPARE_REF_TO_TEXTURE = 0x884E;

}
